<?php

namespace FC\PlatformBundle\Repository;

/**
 * GodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GodRepository extends \Doctrine\ORM\EntityRepository
{
}
